export const CURRENTLY_IN_GAME = 'CURRENTLY_IN_GAME'
export const FATAL_ERROR = 'FATAL_ERROR'
export const KICKED = 'KICKED'
export const KEY_ERROR = 'KEY_ERROR'
export const NICKNAME_ERROR = 'NICKNAME_ERROR'
export const JSON_ERROR = 'JSON_ERROR'
export const GAME_ERROR = 'GAME_ERROR'
export const SNAPSHOT = 'SNAPSHOT'
