/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.smartin.id1212;

public class App {
    public static void main(String[] args) {
        System.out.println("Running");
    }
}
