export const NEW_GAME = 'NEW_GAME'
export const JOIN_GAME = 'JOIN_GAME'
export const MOVE = 'MOVE'
export const CHICAGO = 'CHICAGO'
export const THROW = 'THROW'
export const START_GAME = 'START_GAME'
export const LEAVE_GAME = 'LEAVE_GAME'
export const RESTART_GAME = 'RESTART_GAME'
